version: '3.1'

services:

 mongo-express:
   image: mongo-express
   restart: always
   environment:
     ME_CONFIG_MONGODB_ADMINUSERNAME: aslam
     ME_CONFIG_MONGODB_ADMINPASSWORD: aslam_pass
     ME_CONFIG_MONGODB_URL: mongodb://aslam:aslam_pass@10.5.0.3:27017/
   networks:
     api_net:
       ipv4_address: 10.5.0.4
 product_catelog_api:
    image: aslamimages/product_catelog:latest
    restart: always
    environment:
      username: aslam
      password: aslam_pass
      database: aslam_db
      ip: 10.5.0.3
      port: 27017

    networks:
      api_net:
        ipv4_address: 10.5.0.5

networks:
  api_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
