version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: aslam
      MONGO_INITDB_ROOT_PASSWORD: aslam_pass
    networks:
       test_net:
        ipv4_address: 10.5.0.3
         


networks:
  test_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1